name: flutter_sigma
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.14.0  # Versão estável atual
  firebase_auth: ^4.16.0   # Versão compatível

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
